// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenTimelapseSort.Contexts;

namespace OpenTimelapseSort.Migrations
{
    [DbContext(typeof(ImportContext))]
    [Migration("20201208191401_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageDirectoryid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("fileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fileTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("target")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ImageDirectoryid");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ImageDirectory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Importid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("target")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Importid");

                    b.ToTable("Directories");
                });

            modelBuilder.Entity("Import", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("fetch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("importDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.HasOne("ImageDirectory", null)
                        .WithMany("imageList")
                        .HasForeignKey("ImageDirectoryid");
                });

            modelBuilder.Entity("ImageDirectory", b =>
                {
                    b.HasOne("Import", null)
                        .WithMany("directories")
                        .HasForeignKey("Importid");
                });

            modelBuilder.Entity("ImageDirectory", b =>
                {
                    b.Navigation("imageList");
                });

            modelBuilder.Entity("Import", b =>
                {
                    b.Navigation("directories");
                });
#pragma warning restore 612, 618
        }
    }
}
