// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenTimelapseSort.Contexts;

namespace OpenTimelapseSort.Migrations
{
    [DbContext(typeof(ImportContext))]
    partial class ImportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageDirectoryid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("directoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("fileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fileTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("parentInstance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ImageDirectoryid");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ImageDirectory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("importId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("importId");

                    b.ToTable("ImageDirectory");
                });

            modelBuilder.Entity("Import", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("fetch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("importDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("target")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Import");
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.HasOne("ImageDirectory", null)
                        .WithMany("imageList")
                        .HasForeignKey("ImageDirectoryid");
                });

            modelBuilder.Entity("ImageDirectory", b =>
                {
                    b.HasOne("Import", null)
                        .WithMany("directories")
                        .HasForeignKey("importId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImageDirectory", b =>
                {
                    b.Navigation("imageList");
                });

            modelBuilder.Entity("Import", b =>
                {
                    b.Navigation("directories");
                });
#pragma warning restore 612, 618
        }
    }
}
